version: "3.8"

services:
  database:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data2:/var/lib/mysqldata

  app:
    build: .
    volumes:
      - .:/app:cached
    command: bash -c "rm -f /rails-app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      RAILS_ENV: development

volumes:
  db_data2: