development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rails_birthday_development
  host: database
  port: 3306
  username: root
  password: root
  socket: /var/run/mysqld/mysqlx.sock
  pool: 5
